name: Frontend CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'


jobs:
  validate-and-test-Python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-node@v6
        with:
            node-version: '21'
            cache: 'npm'
            cache-dependency-path: frontend/package.lock.json

      - name: Install Dependencies
        run:  npm ci

      - name: Linting (ESLint)
        run: npm run lint

      - name: Run Tests & Check Coverage
        run: |
          npx nyc --check-coverage --lines 55 npm test